import type { Connector, DiagnosticIssue, GuideStepData, SyncEvent } from './types';

const snGuideSteps: GuideStepData[] = [
  { step: 1, title: 'Name your connector', description: 'Choose a name that will make sense to users when it appears in Copilot search results.', status: 'ok' },
  { step: 2, title: 'Choose user criteria', description: 'Use Simple for role-based access. Use Advanced only if your org has scripted ACLs — note that custom scripts will be partially ignored.', status: 'ok' },
  { step: 3, title: 'Enter your instance URL', description: "Use the full URL of your ServiceNow instance. Confirm it's reachable before continuing — see Connection health if it isn't.", status: 'warn' },
  { step: 4, title: 'Set up authentication', description: "Basic Auth and OAuth 2.0 are supported. If your org uses SSO, you'll need a dedicated service account — see Connection health for guidance.", status: 'warn' },
  { step: 5, title: 'Create and monitor', description: 'Once saved, the first sync begins automatically. Switch to Connection health if the sync stops or reports issues.', status: 'idle' },
];

const snIssues: DiagnosticIssue[] = [
  {
    id: 'sn-1',
    rank: 1,
    severity: 'blocker',
    source: 'mismatch',
    title: 'Authentication refused',
    description: 'Microsoft attempted to sign in using Basic Auth with svc-copilot@contoso.com. ServiceNow returned 403 — the account may have MFA enabled or the password was recently rotated.',
    detectedAt: '2026-03-17T06:02:00Z',
    resolution: 'Disable MFA for this service account in ServiceNow, or switch the connector authentication to OAuth 2.0.',
    resolutionAction: 'fix-in-connector',
    copilotImpact: 'Copilot will resume indexing and surface HR policy content in search results for all users.',
  },
  {
    id: 'sn-2',
    rank: 2,
    severity: 'blocker',
    source: 'servicenow',
    title: 'Service account missing read role',
    description: 'The service account svc-copilot@contoso.com does not have the snc_read role in ServiceNow. Without it, Microsoft cannot index any knowledge articles.',
    detectedAt: '2026-03-17T06:02:00Z',
    resolution: 'In ServiceNow go to User Administration → Users → open the service account → assign the snc_read role.',
    resolutionAction: 'fix-in-servicenow',
    copilotImpact: 'Copilot gains read access to all knowledge articles and can begin indexing them for search.',
  },
  {
    id: 'sn-3',
    rank: 3,
    severity: 'warning',
    source: 'unsupported',
    title: 'Custom ACL scripts partially ignored',
    description: "Your ServiceNow instance uses custom ACL scripts to control article visibility. Microsoft's connector only honours role-based access criteria — scripted ACLs are bypassed, which may expose restricted articles in Copilot results.",
    detectedAt: '2026-03-15T08:15:00Z',
    requiresDiagnostic: true,
    copilotImpact: 'Resolving this ensures Copilot only surfaces articles that users are genuinely permitted to see, reducing the risk of confidential content appearing in results.',
    diagnosticQuestions: [
      {
        id: 'q1',
        question: 'Which articles in ServiceNow are protected by custom ACL scripts?',
        options: [
          { value: 'all', label: 'All knowledge articles' },
          { value: 'some', label: 'Only specific knowledge bases' },
          { value: 'none', label: "None — I'm not sure this applies to us" },
        ],
      },
      {
        id: 'q2',
        question: 'What do the ACL scripts check for?',
        options: [
          { value: 'dept', label: 'Department or team membership' },
          { value: 'location', label: 'User location or region' },
          { value: 'custom-field', label: 'A custom user attribute or field' },
          { value: 'unsure', label: "I'm not sure" },
        ],
      },
    ],
  },
  {
    id: 'sn-4',
    rank: 4,
    severity: 'warning',
    source: 'connector',
    title: 'Crawl scope too broad',
    description: 'The connector is indexing all knowledge bases including HR Confidential and Legal Review. These may contain content not intended for Copilot search results.',
    detectedAt: '2026-03-14T10:30:00Z',
    resolution: 'Go to the Content tab in connector settings and restrict indexing to specific approved knowledge bases only.',
    resolutionAction: 'fix-in-connector',
    copilotImpact: 'Copilot search results will only include approved content, preventing confidential articles from appearing to unauthorised users.',
  },
  {
    id: 'sn-acl',
    rank: 5,
    severity: 'blocker',
    source: 'mismatch',
    title: 'ACL sync failed — zero search results',
    description: 'The connector completed a full crawl and indexed content, but ACL sync silently failed. All users are seeing zero search results in Copilot because no permissions were propagated. This issue can go undetected for days without an explicit health indicator.',
    detectedAt: '2026-03-16T09:15:00Z',
    resolution: 'In ServiceNow, go to User Administration → Users → open the service account → verify that both acl_read and glide_read roles are assigned. Then trigger a manual ACL sync from the connector settings.',
    resolutionAction: 'fix-in-servicenow',
    copilotImpact: 'All users will immediately start seeing search results in Copilot. Permissions will be enforced correctly so each user only sees content they are allowed to access.',
  },
  {
    id: 'sn-5',
    rank: 6,
    severity: 'suggestion',
    source: 'connector',
    title: 'Switch to OAuth 2.0',
    description: 'Basic Auth is currently working but OAuth 2.0 is more secure for long-running connectors. It avoids sync failures when service account passwords are rotated.',
    detectedAt: '2026-03-10T14:00:00Z',
    resolution: 'In connector setup, go to the Setup tab → Authentication type → select OAuth 2.0 and provide a client ID and secret from ServiceNow.',
    resolutionAction: 'fix-in-connector',
    copilotImpact: 'Syncs will continue uninterrupted even when passwords are rotated, keeping Copilot results fresh without admin intervention.',
  },
  {
    id: 'sn-6',
    rank: 7,
    severity: 'suggestion',
    source: 'servicenow',
    title: 'Increase crawl frequency',
    description: 'The connector is set to crawl weekly but 47 new HR policy articles were added in the last 24 hours. Search results in Copilot may lag behind by up to 7 days.',
    detectedAt: '2026-03-16T08:00:00Z',
    resolution: 'In ServiceNow, check if incremental updates are enabled for the knowledge base. Then in connector settings increase the crawl schedule to daily.',
    resolutionAction: 'fix-in-servicenow',
    copilotImpact: 'Copilot will reflect new and updated HR articles within hours instead of days, giving users accurate and timely answers.',
  },
  // Historical resolved issues — used for chart annotations
  {
    id: 'sn-hist-1',
    rank: 0,
    severity: 'blocker',
    source: 'connector',
    title: 'OAuth token expired',
    description: 'The OAuth token used by the connector expired, causing the Mar 11 sync to fail completely. No items were indexed.',
    detectedAt: '2026-03-11T08:02:00Z',
    resolution: 'Refreshed the OAuth token in connector authentication settings.',
    resolutionAction: 'fix-in-connector',
    resolvedAt: '2026-03-11T17:45:00Z',
  },
  {
    id: 'sn-hist-2',
    rank: 0,
    severity: 'warning',
    source: 'servicenow',
    title: 'API rate limit exceeded',
    description: 'ServiceNow API rate limit was hit during the Mar 7 sync, causing only partial indexing of knowledge articles.',
    detectedAt: '2026-03-07T08:05:00Z',
    resolution: 'Reduced concurrent API requests in connector advanced settings.',
    resolutionAction: 'fix-in-connector',
    resolvedAt: '2026-03-07T15:20:00Z',
  },
  {
    id: 'sn-hist-3',
    rank: 0,
    severity: 'blocker',
    source: 'mismatch',
    title: 'SSL certificate mismatch',
    description: 'The SSL certificate on the ServiceNow instance did not match the expected hostname, blocking all connector requests.',
    detectedAt: '2026-03-12T10:00:00Z',
    resolution: 'Updated the instance URL in connector settings to match the certificate subject.',
    resolutionAction: 'fix-in-connector',
    resolvedAt: '2026-03-12T14:10:00Z',
  },
  {
    id: 'sn-hist-4',
    rank: 0,
    severity: 'warning',
    source: 'connector',
    title: 'Throttling on large knowledge base',
    description: 'The HR Policies knowledge base exceeded 50,000 articles, triggering connector throttling and incomplete indexing.',
    detectedAt: '2026-03-13T09:30:00Z',
    resolution: 'Split the knowledge base scope into two separate crawl configurations.',
    resolutionAction: 'fix-in-connector',
    resolvedAt: '2026-03-13T16:50:00Z',
  },
  {
    id: 'sn-hist-5',
    rank: 0,
    severity: 'blocker',
    source: 'servicenow',
    title: 'Knowledge base deactivated',
    description: 'The primary HR knowledge base was accidentally deactivated in ServiceNow, making all articles unavailable to the connector.',
    detectedAt: '2026-03-14T08:05:00Z',
    resolution: 'Reactivated the knowledge base in ServiceNow Knowledge Management settings.',
    resolutionAction: 'fix-in-servicenow',
    resolvedAt: '2026-03-14T11:20:00Z',
  },
];

const snSyncHistory: SyncEvent[] = [
  { id: 'ev-1',  startedAt: '2026-03-17T08:00:00Z', completedAt: '2026-03-17T08:12:00Z', status: 'partial', itemsIndexed: 274,  errorCount: 2 },
  { id: 'ev-2',  startedAt: '2026-03-16T08:00:00Z', completedAt: '2026-03-16T08:14:00Z', status: 'partial', itemsIndexed: 312,  errorCount: 1 },
  { id: 'ev-3',  startedAt: '2026-03-15T08:00:00Z', completedAt: '2026-03-15T08:11:00Z', status: 'success', itemsIndexed: 487,  errorCount: 0 },
  { id: 'ev-4',  startedAt: '2026-03-14T08:00:00Z', completedAt: '2026-03-14T08:10:00Z', status: 'success', itemsIndexed: 501,  errorCount: 0 },
  { id: 'ev-5',  startedAt: '2026-03-13T08:00:00Z', completedAt: '2026-03-13T08:09:00Z', status: 'success', itemsIndexed: 498,  errorCount: 0 },
  { id: 'ev-6',  startedAt: '2026-03-12T08:00:00Z', completedAt: '2026-03-12T08:13:00Z', status: 'partial', itemsIndexed: 410,  errorCount: 3 },
  { id: 'ev-7',  startedAt: '2026-03-11T08:00:00Z', completedAt: '2026-03-11T08:07:00Z', status: 'failed',  itemsIndexed: 0,    errorCount: 8 },
  { id: 'ev-8',  startedAt: '2026-03-10T08:00:00Z', completedAt: '2026-03-10T08:11:00Z', status: 'success', itemsIndexed: 492,  errorCount: 0 },
  { id: 'ev-9',  startedAt: '2026-03-09T08:00:00Z', completedAt: '2026-03-09T08:12:00Z', status: 'success', itemsIndexed: 488,  errorCount: 0 },
  { id: 'ev-10', startedAt: '2026-03-08T08:00:00Z', completedAt: '2026-03-08T08:10:00Z', status: 'success', itemsIndexed: 475,  errorCount: 0 },
  { id: 'ev-11', startedAt: '2026-03-07T08:00:00Z', completedAt: '2026-03-07T08:14:00Z', status: 'partial', itemsIndexed: 340,  errorCount: 2 },
  { id: 'ev-12', startedAt: '2026-03-06T08:00:00Z', completedAt: '2026-03-06T08:11:00Z', status: 'success', itemsIndexed: 462,  errorCount: 0 },
];

const jiraGuideSteps: GuideStepData[] = [
  { step: 1, title: 'Name your connector', description: 'Connector name used in Copilot search results.', status: 'ok' },
  { step: 2, title: 'Choose user criteria', description: 'Role-based access using Jira project permissions.', status: 'ok' },
  { step: 3, title: 'Enter your instance URL', description: 'The full URL of your Jira Cloud instance.', status: 'ok' },
  { step: 4, title: 'Set up authentication', description: 'OAuth 2.0 configured with Atlassian app credentials.', status: 'ok' },
  { step: 5, title: 'Create and monitor', description: 'Sync is running on schedule. No issues detected.', status: 'ok' },
];

const jiraSyncHistory: SyncEvent[] = [
  { id: 'jv-1',  startedAt: '2026-03-16T06:00:00Z', completedAt: '2026-03-16T06:08:00Z', status: 'success', itemsIndexed: 1203, errorCount: 0 },
  { id: 'jv-2',  startedAt: '2026-03-15T06:00:00Z', completedAt: '2026-03-15T06:07:00Z', status: 'success', itemsIndexed: 1198, errorCount: 0 },
  { id: 'jv-3',  startedAt: '2026-03-14T06:00:00Z', completedAt: '2026-03-14T06:09:00Z', status: 'success', itemsIndexed: 1190, errorCount: 0 },
  { id: 'jv-4',  startedAt: '2026-03-13T06:00:00Z', completedAt: '2026-03-13T06:08:00Z', status: 'success', itemsIndexed: 1185, errorCount: 0 },
  { id: 'jv-5',  startedAt: '2026-03-12T06:00:00Z', completedAt: '2026-03-12T06:07:00Z', status: 'success', itemsIndexed: 1201, errorCount: 0 },
  { id: 'jv-6',  startedAt: '2026-03-11T06:00:00Z', completedAt: '2026-03-11T06:09:00Z', status: 'success', itemsIndexed: 1196, errorCount: 0 },
  { id: 'jv-7',  startedAt: '2026-03-10T06:00:00Z', completedAt: '2026-03-10T06:08:00Z', status: 'success', itemsIndexed: 1188, errorCount: 0 },
  { id: 'jv-8',  startedAt: '2026-03-09T06:00:00Z', completedAt: '2026-03-09T06:07:00Z', status: 'success', itemsIndexed: 1177, errorCount: 0 },
  { id: 'jv-9',  startedAt: '2026-03-08T06:00:00Z', completedAt: '2026-03-08T06:09:00Z', status: 'success', itemsIndexed: 1182, errorCount: 0 },
  { id: 'jv-10', startedAt: '2026-03-07T06:00:00Z', completedAt: '2026-03-07T06:08:00Z', status: 'success', itemsIndexed: 1175, errorCount: 0 },
  { id: 'jv-11', startedAt: '2026-03-06T06:00:00Z', completedAt: '2026-03-06T06:07:00Z', status: 'success', itemsIndexed: 1168, errorCount: 0 },
  { id: 'jv-12', startedAt: '2026-03-05T06:00:00Z', completedAt: '2026-03-05T06:09:00Z', status: 'success', itemsIndexed: 1160, errorCount: 0 },
];

const confluenceGuideSteps: GuideStepData[] = [
  { step: 1, title: 'Name your connector', description: 'Connector name used in Copilot search results.', status: 'ok' },
  { step: 2, title: 'Choose user criteria', description: 'Space-based permissions from Confluence.', status: 'ok' },
  { step: 3, title: 'Enter your instance URL', description: 'Full URL of your Confluence Cloud instance.', status: 'ok' },
  { step: 4, title: 'Set up authentication', description: 'Basic Auth configured, first sync pending.', status: 'ok' },
  { step: 5, title: 'Create and monitor', description: 'First sync has not started yet. It will begin shortly.', status: 'idle' },
];

export const CONNECTORS: Connector[] = [
  {
    id: 'hr-policies',
    displayName: 'HR Policies',
    connectorType: 'HR Web',
    logoUrl: '/8ea55b65f2f4f34a4a05e79ddc164a85f0b2572d.png',
    userCriteriaType: 'simple',
    instanceUrl: 'https://contoso.service-now.com',
    authMethod: 'basic',
    healthStatus: 'healthy',
    blockerCount: 3,
    warningCount: 2,
    suggestionCount: 2,
    issues: snIssues,
    guideSteps: snGuideSteps,
    syncHistory: snSyncHistory,
    createdAt: '2026-03-17T14:00:00Z',
    lastSyncAt: '2026-03-24T10:32:00Z',
  },
  {
    id: 'hr-restrictions',
    displayName: 'HR Restrictions',
    connectorType: 'HR Web',
    logoUrl: '/8ea55b65f2f4f34a4a05e79ddc164a85f0b2572d.png',
    userCriteriaType: 'simple',
    instanceUrl: 'https://contoso.atlassian.net',
    authMethod: 'oauth2',
    healthStatus: 'healthy',
    blockerCount: 0,
    warningCount: 0,
    suggestionCount: 0,
    issues: [],
    guideSteps: jiraGuideSteps,
    syncHistory: jiraSyncHistory,
    createdAt: '2026-03-17T10:00:00Z',
    lastSyncAt: '2026-03-22T09:15:00Z',
  },
  {
    id: 'hr-benefits',
    displayName: 'HR Benefits',
    connectorType: 'HR Web',
    logoUrl: '/8ea55b65f2f4f34a4a05e79ddc164a85f0b2572d.png',
    userCriteriaType: 'simple',
    instanceUrl: 'https://contoso.atlassian.net/wiki',
    authMethod: 'basic',
    healthStatus: 'healthy',
    blockerCount: 0,
    warningCount: 0,
    suggestionCount: 0,
    issues: [],
    guideSteps: confluenceGuideSteps,
    syncHistory: [],
    createdAt: '2026-03-17T10:00:00Z',
    lastSyncAt: '2026-03-02T14:20:00Z',
  },
];
